"""Create the Adelin v2 expanded/new-sample diagnostic plan.

This script writes pre-registered plan artifacts only. It does not read OHLC,
collect samples, run replay, run matched controls, or inspect candles.
"""
from __future__ import annotations

import argparse
import json
from pathlib import Path
from typing import Any


PLAN_VERSION = "adelin_v2_good_fast_expanded_sample_plan_v1"
DEFAULT_OUTPUT_DIR = Path("backtests/reports/adelin_v2_good_fast_expanded_sample_plan")

POST_HOC_HYPOTHESIS_ORIGIN_DISCLOSURE = {
    "hypothesis_origin": "post_hoc_from_underpowered_exploratory_diagnostic",
    "originating_good_fast_reaction_n": 10,
    "originating_fast_failure_n": 27,
    "originating_verdict": "MIXED_AMBIGUOUS_SMALL_N",
    "validation_status": "not_validated",
    "may_be_rejected_by_future_test": True,
    "not_deployment_evidence": True,
    "disclosure": (
        "H1 and H2 were selected from a prior underpowered exploratory diagnostic "
        "with GOOD_FAST_REACTION N=10, FAST_FAILURE N=27, and final verdict "
        "MIXED_AMBIGUOUS_SMALL_N. "
        "They are post-hoc hypotheses, not validated features. The expanded/new-sample "
        "plan is allowed only to test whether these hypotheses repeat on new or expanded "
        "samples. The future test may reject both hypotheses. These hypotheses must not "
        "be treated as edge, filters, scoring components, or deployment evidence."
    ),
}

PRIMARY_HYPOTHESES = [
    {
        "hypothesis_id": "H1",
        "feature_name": "fvg_ifvg_near_20p",
        "role": "PRIMARY_HYPOTHESIS",
        **POST_HOC_HYPOTHESIS_ORIGIN_DISCLOSURE,
        "prior_observation": {
            "good_fast_reaction": "3/10",
            "fast_failure": "23/27",
            "difference_good_minus_fast": -0.552,
        },
        "frozen_interpretation": (
            "Presence of nearby FVG/iFVG may be associated with FAST_FAILURE; "
            "treat as a possible negative/failure marker."
        ),
        "future_test_requirements": [
            "deterministic definition",
            "pre-entry only",
            "no post-entry candles",
            "same threshold: near 20 pips",
            "report present/absent by group",
            "report direction confidence sensitivity",
            "do not reinterpret as positive unless future data proves otherwise",
        ],
    },
    {
        "hypothesis_id": "H2",
        "feature_name": "liquidity_htf_recent_level",
        "role": "PRIMARY_HYPOTHESIS",
        **POST_HOC_HYPOTHESIS_ORIGIN_DISCLOSURE,
        "prior_observation": {
            "good_fast_reaction": "6/10",
            "fast_failure": "3/27",
            "difference_good_minus_fast": 0.489,
        },
        "frozen_interpretation": (
            "Recent HTF liquidity confluence may be associated with GOOD_FAST_REACTION; "
            "treat as a possible positive/good-reaction marker."
        ),
        "future_test_requirements": [
            "deterministic definition",
            "pre-entry only",
            "define what counts as HTF",
            "define recency window before execution",
            "no outcome-derived threshold selection",
            "report present/absent by group",
            "report direction confidence sensitivity",
        ],
    },
]

SECONDARY_TRACKED_FEATURES = [
    {
        "feature_name": "m1_large_body_ge_0_60",
        "role": "SECONDARY_TRACKED_ONLY",
        "promotion_rule": "May not become a primary hypothesis unless a later plan explicitly promotes it.",
    },
    {
        "feature_name": "m1_close_high_ge_0_70",
        "role": "SECONDARY_TRACKED_ONLY",
        "promotion_rule": "May not become a primary hypothesis unless a later plan explicitly promotes it.",
    },
]

MINIMUM_N_GATES = {
    "target_total_expanded_samples": 80,
    "hard_minimum_total_samples_for_useful_expanded_diagnostic": 60,
    "target_good_fast_reaction_n": 20,
    "hard_minimum_good_fast_reaction_n": 11,
    "previous_gate_clearance_rule": "GOOD_FAST_REACTION N must be > 10 to clear the previous gate.",
    "if_good_fast_reaction_n_lte_10": {
        "strongest_allowed_verdict": "MIXED_AMBIGUOUS_SMALL_N",
        "phase_4_blocked": True,
    },
    "target_fast_failure_n": 40,
    "hard_minimum_fast_failure_n": 25,
    "direction_confidence": {
        "report_confidence_3_and_2_separately": True,
        "confidence_3_only_sensitivity_mandatory": True,
        "confidence_2_only_signal_policy": "mark weak/research-only and do not proceed to Phase 4",
    },
}

SAMPLE_COLLECTION_SCHEMA = {
    "allowed_sources": [
        "existing historical candidate metadata if not already used",
        "newly generated visual review candidates only if generated by pre-existing candidate rules",
        "future OOS/paper samples if available",
    ],
    "required_fields": [
        "decision_timestamp",
        "direction",
        "direction_source",
        "direction_confidence",
        "pre_entry_only",
        "used_post_entry_data",
        "diagnostic_outcome_group",
        "sample_source",
        "candidate_source",
        "session",
        "hour",
        "date",
        "symbol",
    ],
    "sample_selection_rule": (
        "New samples must be selected using pre-defined sample collection criteria only, "
        "not because they support or refute H1/H2."
    ),
    "primary_comparison_groups": ["GOOD_FAST_REACTION", "FAST_FAILURE"],
    "secondary_review_groups": ["MIXED_REACTION", "CHOP_AFTER_ENTRY"],
}

INCLUSION_EXCLUSION_RULES = {
    "inclusion": [
        "XAUUSD only",
        "Adelin v2 only",
        "pre-entry metadata available",
        "direction known or recoverable using frozen rule adelin_v2_pre_decision_sweep_v1",
        "outcome group is GOOD_FAST_REACTION, FAST_FAILURE, MIXED_REACTION, or CHOP_AFTER_ENTRY",
    ],
    "primary_comparison_inclusion": ["GOOD_FAST_REACTION", "FAST_FAILURE"],
    "secondary_groups_excluded_from_primary": ["MIXED_REACTION", "CHOP_AFTER_ENTRY"],
    "exclusion": [
        "unknown direction after frozen recovery rule",
        "post-entry direction inference",
        "missing decision_timestamp",
        "missing required metadata",
        "leakage risk",
        "duplicate sample/candidate",
        "samples selected manually because they look good or look bad",
    ],
}

FUTURE_EXECUTION_SCHEMA = {
    "allowed": [
        "collect/select additional samples according to this plan",
        "compute H1/H2 present/absent by group",
        "track secondary features as secondary only",
        "stratify by direction confidence and direction source",
        "run confidence-3-only sensitivity",
        "write leakage check report",
    ],
    "forbidden": [
        "convert H1/H2 into live filters",
        "build a score",
        "optimize thresholds",
        "pick new thresholds after seeing results",
        "use post-entry candles to define features",
        "claim profitability",
        "claim statistical significance",
        "claim deployability",
        "unlock Phase 4 automatically",
        "run matched-control replay",
    ],
    "feature_definitions": {
        "fvg_ifvg_near_20p": {
            "threshold": "20 pips",
            "feature_role": "primary negative/failure-side hypothesis",
            "pre_entry_only": True,
        },
        "liquidity_htf_recent_level": {
            "feature_role": "primary positive/good-reaction-side hypothesis",
            "pre_entry_only": True,
            "htf_definition": "H1 recent high/low from the prior 24h or M15 recent high/low from the prior 6h.",
            "recency_window": "H1: [decision_timestamp - 24h, decision_timestamp); M15: [decision_timestamp - 6h, decision_timestamp).",
            "excluded_timeframes": ["M5", "M1"],
        },
    },
}

DECISION_MATRIX = {
    "phase_4_blocked": True,
    "outcomes": [
        {
            "decision_code": "HYPOTHESES_REPEAT_WITH_SUFFICIENT_N",
            "condition": "H1/H2 repeat directionally on expanded samples and minimum-N gates pass.",
            "allowed_next_step": "allow bounded confirmatory diagnostic",
            "phase_4_status": "still blocked; no automatic Phase 4",
        },
        {
            "decision_code": "H1_H2_FAIL_TO_REPEAT",
            "condition": "Candidate feature directions do not repeat.",
            "allowed_next_step": "reject as sample-specific and pause Adelin v2 strategy path",
            "phase_4_status": "blocked",
        },
        {
            "decision_code": "CONFIDENCE_2_ONLY_SIGNAL",
            "condition": "Signal exists only in confidence-2 direction-inferred samples.",
            "allowed_next_step": "mark weak and require more confidence-3 samples",
            "phase_4_status": "blocked",
        },
        {
            "decision_code": "MINIMUM_N_NOT_MET",
            "condition": "Minimum-N gates fail.",
            "allowed_next_step": "verdict capped at MIXED_AMBIGUOUS_SMALL_N; more samples required",
            "phase_4_status": "blocked",
        },
        {
            "decision_code": "LEAKAGE_DETECTED",
            "condition": "Feature uses post-entry information.",
            "allowed_next_step": "reject",
            "phase_4_status": "blocked",
        },
    ],
}


def expanded_sample_plan() -> dict[str, Any]:
    return {
        "plan_version": PLAN_VERSION,
        "plan_only": True,
        "context": {
            "prior_execution_commit": "60824ca",
            "prior_verdict": "MIXED_AMBIGUOUS_SMALL_N",
            "phase_4_blocked": True,
            "good_fast_reaction_n": 10,
            "fast_failure_n": 27,
            "leakage_check_passed": True,
        },
        "goal": "Freeze expanded/new-sample collection rules before any new sample execution.",
        "primary_hypotheses": [item["feature_name"] for item in PRIMARY_HYPOTHESES],
        "hypothesis_origin_disclosure": POST_HOC_HYPOTHESIS_ORIGIN_DISCLOSURE,
        "secondary_tracked_features": [item["feature_name"] for item in SECONDARY_TRACKED_FEATURES],
        "minimum_n_gates": MINIMUM_N_GATES,
        "sample_collection_schema_file": "sample_collection_schema.json",
        "decision_matrix_file": "decision_matrix.json",
    }


def summary() -> dict[str, Any]:
    return {
        "plan_version": PLAN_VERSION,
        "plan_only": True,
        "samples_collected": False,
        "ohlc_read": False,
        "candles_inspected": False,
        "replay_run": False,
        "matched_control_replay_run": False,
        "phase_4_blocked": True,
        "live_trading_enabled": False,
        "orders_enabled": False,
        "telegram_enabled": False,
        "broker_execution_enabled": False,
        "profitability_claim_made": False,
        "runtime_logic_modified": False,
        "strategy_2_touched": False,
        "strategy_3_touched": False,
        "v3_stash_applied_or_popped": False,
        "primary_hypotheses": [item["feature_name"] for item in PRIMARY_HYPOTHESES],
        "hypothesis_origin_disclosure": POST_HOC_HYPOTHESIS_ORIGIN_DISCLOSURE,
        "secondary_tracked_features": [item["feature_name"] for item in SECONDARY_TRACKED_FEATURES],
        "minimum_n_gates": MINIMUM_N_GATES,
        "forbidden_interpretations": FUTURE_EXECUTION_SCHEMA["forbidden"],
        "verdict_flags": [
            "EXPANDED_SAMPLE_PLAN_REGISTERED",
            "PLAN_ONLY_NO_SAMPLES_COLLECTED",
            "NO_OHLC_READ",
            "PRIMARY_HYPOTHESES_FROZEN",
            "POST_HOC_HYPOTHESIS_ORIGIN_DISCLOSED",
            "MINIMUM_N_GATES_REGISTERED",
            "PHASE_4_STILL_BLOCKED",
            "NO_MATCHED_CONTROL_REPLAY",
            "ADELIN_REMAINS_RESEARCH_ONLY",
            "NO_LIVE_DEPLOYMENT_DECISION",
        ],
    }


def write_json(path: Path, payload: Any) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(json.dumps(payload, indent=2, sort_keys=True) + "\n", encoding="utf-8")


def write_plan(output_dir: Path) -> dict[str, Path]:
    output_dir.mkdir(parents=True, exist_ok=True)
    outputs = {
        "expanded_sample_plan": output_dir / "expanded_sample_plan.json",
        "frozen_hypotheses": output_dir / "frozen_hypotheses.json",
        "sample_collection_schema": output_dir / "sample_collection_schema.json",
        "inclusion_exclusion_rules": output_dir / "inclusion_exclusion_rules.json",
        "minimum_n_gates": output_dir / "minimum_n_gates.json",
        "future_execution_schema": output_dir / "future_execution_schema.json",
        "decision_matrix": output_dir / "decision_matrix.json",
        "summary": output_dir / "summary.json",
    }
    write_json(outputs["expanded_sample_plan"], expanded_sample_plan())
    write_json(
        outputs["frozen_hypotheses"],
        {
            "plan_version": PLAN_VERSION,
            "hypothesis_origin_disclosure": POST_HOC_HYPOTHESIS_ORIGIN_DISCLOSURE,
            "primary_hypotheses": PRIMARY_HYPOTHESES,
            "secondary_tracked_features": SECONDARY_TRACKED_FEATURES,
        },
    )
    write_json(outputs["sample_collection_schema"], SAMPLE_COLLECTION_SCHEMA)
    write_json(outputs["inclusion_exclusion_rules"], INCLUSION_EXCLUSION_RULES)
    write_json(outputs["minimum_n_gates"], MINIMUM_N_GATES)
    write_json(outputs["future_execution_schema"], FUTURE_EXECUTION_SCHEMA)
    write_json(outputs["decision_matrix"], DECISION_MATRIX)
    write_json(outputs["summary"], summary())
    return outputs


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--output-dir", type=Path, default=DEFAULT_OUTPUT_DIR)
    return parser.parse_args()


def main() -> int:
    args = parse_args()
    outputs = write_plan(args.output_dir)
    print(json.dumps({key: str(path) for key, path in outputs.items()}, indent=2, sort_keys=True))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
